examples: legacy_apps: Fix add default routines for suspend/resume
Fix following build warning introduced by:

89f56feaec6d ("examples: legacy_apps: Add default routines for suspend/resume")

system/linux/machine/generic/platform_info.c:546:3:
warning: implicit declaration of function ‘system_suspend’ [-Wimplicit-function-declaration]
  546 |   system_suspend();
      |   ^~~~~~~~~~~~~~

Signed-off-by: Arnaud Pouliquen <arnaud.pouliquen@foss.st.com>